##----------- Pywall -----------##
#[colors]
#background = ${xrdb:color0:#222}
#foreground = ${xrdb:color7:#222}
#foreground-alt = ${xrdb:color7:#222}
#primary = ${xrdb:color1:#222}
#secondary = ${xrdb:color2:#222}
#lert = ${xrdb:color3:#222}

##------------ Sea -------------##
[colors]
background = #1b1e24
background-alt = #373B41
foreground = #CBFAFF
primary = #3393FF
secondary = #8ABEB7
alert = #A54242
disabled = #707880

##---------- One Shot ----------##
# [colors]
# background = #13131b
# background-alt = #373B41
# foreground = #ffffff
# primary = #3393FF
# secondary = #8ABEB7
# alert = #A54242
# disabled = #707880
